/* Named beatmap-bg, NOT beatmap-background — Netlify treats any function
   filename ending in "-background" as a fire-and-forget Background
   Function (always responds 202 with an empty body immediately, actual
   execution happens out-of-band). Confirmed live via `netlify dev`: this
   file under its original name never returned the image at all. Keep this
   name.

   Extracts the REAL in-game background image for a beatmapset, for Watch
   Replay's theater background. osu!'s CDN `covers/cover.jpg` is a
   pre-cropped ~3.6:1 promo banner generated by osu! itself — no amount of
   CSS background-size/aspect-ratio tuning can recover the parts it already
   cropped, which is why the theater background never showed the "full"
   image no matter how the box was resized (confirmed live this session:
   a sampled cover.jpg came back 900x250). replayviewer.com instead
   downloads the whole mapset and reads the real background straight out of
   it (confirmed by reading its own bundled source, which fetches
   `osu.direct/api/d/{beatmapset_id}`) — this does the same thing.

   GET ?beatmapset_id=<id>&beatmap_id=<id optional>. Checks
   getBeatmapBackgroundStore() first (`bg:{beatmapset_id}`) — a ranked/loved
   mapset's files never change, so this is cached forever, same policy as
   beatmap-file.js and replay-download.js. On a miss:
     1. Download the .osz from osu.direct's mirror (`?noVideo=1` — only the
        background image is needed, skip the multi-MB video track some
        mapsets bundle).
     2. Unzip with fflate (already a project dependency client-side; kept
        deliberately minimal here rather than adding a heavier zip library
        for a single-file extraction).
     3. Read the FIRST *.osu entry's [Events] section for its
        `0,0,"filename",0,0` Background line — verified live this session:
        every difficulty in a mapset normally shares one background, so
        beatmap_id (a specific difficulty) is accepted but not required;
        picking any one difficulty's .osu is sufficient in the common case.
     4. Extract that exact file (case-insensitive, backslash-normalised —
        old maps occasionally used Windows-style paths) and cache+return it.
   Real background images run close to widescreen (a live-sampled example
   came back 1800x975, ratio 1.85 — near 16:9) unlike cover.jpg's crop, so
   the frontend can keep using CSS `background-size: cover` on the same
   16:9 theater box and this alone visibly stops loosing most of the image. */
const { unzipSync, strFromU8 } = require('fflate');
const { getBeatmapBackgroundStore } = require('./_blobs-store');

const CONTENT_TYPES = { jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png' };

function findBackgroundFilename(osuText) {
    const eventsStart = osuText.search(/^\[Events\]/m);
    if (eventsStart === -1) return null;
    const eventsSection = osuText.slice(eventsStart, osuText.indexOf('\n[', eventsStart + 1) === -1 ? undefined : osuText.indexOf('\n[', eventsStart + 1));
    const m = eventsSection.match(/^0,0,"?([^",\r\n]+)"?/m);
    return m ? m[1].replace(/\\/g, '/').split('/').pop() : null;
}

exports.handler = async (event) => {
    const corsHeaders = { 'Access-Control-Allow-Origin': '*' };
    if (event.httpMethod === 'OPTIONS') return { statusCode: 200, headers: corsHeaders, body: '' };
    if (event.httpMethod !== 'GET') {
        return { statusCode: 405, headers: { ...corsHeaders, 'Content-Type': 'application/json' }, body: JSON.stringify({ error: 'Method not allowed' }) };
    }

    const jsonHeaders = { ...corsHeaders, 'Content-Type': 'application/json' };
    const beatmapsetId = (event.queryStringParameters || {}).beatmapset_id;
    if (!beatmapsetId || !/^\d+$/.test(beatmapsetId)) {
        return { statusCode: 400, headers: jsonHeaders, body: JSON.stringify({ error: 'beatmapset_id is required' }) };
    }

    try {
        const cacheStore = getBeatmapBackgroundStore();
        const bytesKey = `bg:${beatmapsetId}`;
        const metaKey = `bg-meta:${beatmapsetId}`;
        const cachedBytes = await cacheStore.get(bytesKey, { type: 'arrayBuffer' });
        if (cachedBytes) {
            const meta = (await cacheStore.get(metaKey, { type: 'json' })) || {};
            return {
                statusCode: 200,
                headers: { ...corsHeaders, 'Content-Type': meta.contentType || 'image/jpeg', 'Cache-Control': 'public, max-age=604800' },
                body: Buffer.from(cachedBytes).toString('base64'),
                isBase64Encoded: true,
            };
        }

        const oszRes = await fetch(`https://osu.direct/api/d/${beatmapsetId}?noVideo=1`);
        if (!oszRes.ok) {
            return { statusCode: oszRes.status === 404 ? 404 : 502, headers: jsonHeaders, body: JSON.stringify({ error: `mirror returned ${oszRes.status}` }) };
        }
        const oszBuf = new Uint8Array(await oszRes.arrayBuffer());

        const entries = unzipSync(oszBuf, { filter: f => !f.dir });
        const osuEntryName = Object.keys(entries).find(n => /\.osu$/i.test(n));
        if (!osuEntryName) {
            return { statusCode: 404, headers: jsonHeaders, body: JSON.stringify({ error: 'no .osu file in mapset' }) };
        }
        const osuText = strFromU8(entries[osuEntryName]);
        const bgFilename = findBackgroundFilename(osuText);
        if (!bgFilename) {
            return { statusCode: 404, headers: jsonHeaders, body: JSON.stringify({ error: 'no background declared' }) };
        }

        const bgEntryName = Object.keys(entries).find(n => n.split(/[\\/]/).pop().toLowerCase() === bgFilename.toLowerCase());
        if (!bgEntryName) {
            return { statusCode: 404, headers: jsonHeaders, body: JSON.stringify({ error: 'background file missing from mapset' }) };
        }

        const ext = (bgEntryName.split('.').pop() || '').toLowerCase();
        const contentType = CONTENT_TYPES[ext] || 'application/octet-stream';
        const bgBytes = entries[bgEntryName];

        await cacheStore.set(bytesKey, Buffer.from(bgBytes));
        await cacheStore.setJSON(metaKey, { contentType });

        return {
            statusCode: 200,
            headers: { ...corsHeaders, 'Content-Type': contentType, 'Cache-Control': 'public, max-age=604800' },
            body: Buffer.from(bgBytes).toString('base64'),
            isBase64Encoded: true,
        };
    } catch (err) {
        return { statusCode: 500, headers: jsonHeaders, body: JSON.stringify({ error: err.message }) };
    }
};
